#debug: true

server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#  main:
#    allow-bean-definition-overriding:true   # 允许重复服务

# 允许预检请求
#  mvc:
#    dispatch-options-request: true

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  #java代码实体类驼峰式命名，数据库表字段以“_”分割，查询语句映射出问题解决

#jwt
jwt:
#  header: Authorization
  # 令牌前缀
#  token-start-with: Bearer
  # 使用Base64对该令牌进行编码
  SECRET:  testtesttesttesttesttest  #XXXXXXXXXXXXXXXX(制定您的密钥)
  # 令牌过期时间 此处单位/毫秒
  EXPIRE_TIME: 14400000

  SUBJECT: LMS

# 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false
  params: count=countSql
  supportMethodsArguments: true

#日志
logging:
  level:
    root: info #（key:包名）
  file:
#    path: log/
    name: log/springDemo.log # 该属性用来配置日志文件名，如果该属性不配置，默认文件名为spring.log


#  说明：
#
#  helperDialect：指定数据库，不指定会自动检测数据库类型
#
#  reasonable：合理化参数，默认false，
#
#  true：页码小于1，查询第一页数据，页码大于总数时，返回最后一页数据；
#  false：页码小于等于1都返回第一页数据，页码大于总数时返回空
#  supportMethodsArguments：默认false，true：分页插件根据params中取值，找到合适值，就自动分页



#test git


